### ISSUE TITLE
How to use SHT31 with I2C address 0x45

### ISSUE THREAD

**Issue by mhaack** [winkj/arduino-sht#5]
Hello,

this is a question for the Sensation library for the SHT3x sensors. How can init the library for a SHT31 sensor with I2C address 0x45?

Thx
Markus

**Comment by winkj** [comment]
Hi Markus,

I'd recommend switching to the official Sensirion library (which is based on this repository) here:
  https://github.com/Sensirion/arduino-sht/
There's an integrated sample (sht-autodetect) which will scan the bus, and automatically instantiate the sensor, inclding the SHT31 on address 0x45.

If you wanna stick with winkj/arduino-sht, there's a setAddress(...) command on the SHT3X class. There's an included example (sht3x.ino) that uses that call to switch to 0x45.

Hope this helps!
